# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    env: 
      TELEGRAM_TOO: ${{secrets.TELEGRAM_TO}}
    steps:
    - uses: actions/checkout@master
    - name: commands
      run: |
        echo $env.TELEGRAM_TOO
        
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      if: env.TELEGRAM_TOO
      with:
        to: ${{ secrets.TELEGRAM_TOO }}
        token: ${{ secrets.TELEGRAM_OKEN }}
        args: The ${{ github.event_name }} event triggered first step.

