# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    runs-on: ubuntu-latest
    env: 
      TELEGRAM_TOO: ${{secrets.TELEGRAM_TO}}
      DAY_OF_WEEK: Mon

    steps:
    - name: "Hello world when it's Monday"
      if: true
      run: echo "Hello $FIRST_NAME $middle_name $Last_Name, today is Monday!"
      env:
        FIRST_NAME: Mona
        middle_name: The
        Last_Name: Octocat

    - uses: actions/checkout@master
    - name: checkout
      if: ${{ failure() && env.TELEGRAM_TOO }}
      run: |
        echo $TELEGRAM_TOO
        echo ${{ env.TELEGRAM_TOO }}
        TELEGRAM_TOO='222'
        echo "TELEGRAM_TO=${{secrets.TELEGRAM_TO}}" >> $GITHUB_ENV
        
    - name: commands
      run: |
        echo $TELEGRAM_TOO
        echo ${{ env.TELEGRAM_TO }}
        echo $secrets.TELEGRAM_TO
        
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      if: env.TELEGRAM_TOO
      env:
        tv: ${{env.TELEGRAM_NO}}
      with:
        to: ${{ env.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOEN }}
        args: The ${{ github.event_name }} event triggered first step.

