# This is a basic workflow to help you get started with Actions

name: debug an action runner

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: Where to run
        options:
        - ubuntu-20.04
        - ubuntu-22.04
        - macos-11
        - macos-12
        - macos-13
        - macos-12-xl
        - macos-13-xl
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ github.event.inputs.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: init
      run: |
        echo "strDate=$(TZ=UTC-8 date +%Y-%m-%d)" >> $GITHUB_ENV
        sudo apt -y install language-pack-zh-hans
        sudo locale-gen
        sudo localectl set-locale LANG=zh_CN.UTF-8

    - name: Start SSH via tmate
      uses: klever1988/ssh2actions@main
      with:
        mode: ssh
      # Send connection info to Telegram (optional)
      # You can find related documents here: https://core.telegram.org/bots
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        SSH_PASSWORD: ${{secrets.SSH_PASSWORD}}
        SSH_PUBKEY: ${{secrets.SSH_PUBKEY}}
        SSH_PRIKEY: ${{secrets.SSH_PRIKEY}}
        NGROK_TOKEN: ${{secrets.NGROK_TOKEN}}
        TUNNEL_HOST: ${{secrets.TUNNEL_HOST}}



