name: distcc_node
on:
  push:
    paths:
      - '.github/workflows/distt_node.yml'
      
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: SSH connection to Actions
      run: |
        sudo apt update
        sudo apt install distcc sshpass
        sudo service distcc stop
        distccd -a 0.0.0.0/0 --daemon
        curl 127.0.0.1:3632
        sshpass -p '4X1MvE9*du' ssh -oStrictHostKeyChecking=no -R 4001:127.0.0.1:3236 root@167.172.214.91
        #sleep 3600
