# This is a basic workflow to help you get started with Actions
name: genwiniso

on:

  workflow_dispatch:

jobs:
  build:
    #defaults:
      #run:
        #working-directory: '/c/build'
    runs-on: windows-latest

    steps:

      - name: Run a multi-line script
        shell: bash
        run: |
          echo test
          df -h /c/ /d/
          pwd
          #Invoke-WebRequest -Uri "https://uupdump.net/get.php?id=ba4aa62b-a402-4985-a6e3-26a6e9d248a1&pack=zh-cn&edition=professional&autodl=2" -OutFile u.zip
          curl -o u.zip -d 'updates=0' 'https://uupdump.net/get.php?id=ba4aa62b-a402-4985-a6e3-26a6e9d248a1&pack=zh-cn&edition=professional&autodl=2'
          #Expand-Archive -Path .\u.zip -DestinationPath uupbuild\
          unzip u.zip -d /c/uupbuild
          cd /c/uupbuild
          ln=`grep -n :START_PROCESS uup_download_windows.cmd | tail -n1 | cut -f1 -d':'`
          sed -i 1,${ln}d uup_download_windows.cmd
          #sed -i '/call convert-UUP.cmd/i\echo 0>input' uup_download_windows.cmd
          #sed -i 's/call convert-UUP.cmd/call convert-UUP.cmd<input/' uup_download_windows.cmd
          #cat uup_download_windows.cmd
          sed -i 's/AddUpdates\s*=1/AddUpdates=0/' ConvertConfig.ini
          cd files
          7z.exe x uup-converter-wimlib.7z -otmpdir
          sed -i '/Press 0/a\echo 0>input' tmpdir/convert-UUP.cmd
          sed -i 's/choice \/c 0 \/n/choice \/c 0 \/n<input/' tmpdir/convert-UUP.cmd
          cd tmpdir; 7z.exe u ../uup-converter-wimlib.7z .
          cd -; rm -rf tmpdir/


      - name: build
        shell: cmd
        working-directory: C:\uupbuild
        run: call uup_download_windows.cmd
          
          
