# This is a basic workflow to help you get started with Actions
name: genwiniso

on:

  workflow_dispatch:

jobs:
  build:
    #defaults:
      #run:
        #working-directory: '/c/build'
    runs-on: windows-latest

    steps:

      - name: Run a multi-line script
        shell: bash
        run: |
          echo test
          df -h /c/ /d/
          pwd
          #Invoke-WebRequest -Uri "https://uupdump.net/get.php?id=ba4aa62b-a402-4985-a6e3-26a6e9d248a1&pack=zh-cn&edition=professional&autodl=2" -OutFile u.zip
          curl -o u.zip -d 'updates=0' 'https://uupdump.net/get.php?id=ba4aa62b-a402-4985-a6e3-26a6e9d248a1&pack=zh-cn&edition=professional&autodl=2'
          #Expand-Archive -Path .\u.zip -DestinationPath uupbuild\
          unzip u.zip -d /c/uupbuild
          cd /c/uupbuild
          ln=`grep -n :START_PROCESS uup_download_windows.cmd | tail -n1 | cut -f1 -d':'`
          sed -i 1,${ln}d uup_download_windows.cmd
          cd files
          7za.exe x uup-converter-wimlib.7z -otmpdir
          sed -i '/choice/d' tmpdir/convert-UUP.cmd
          cd tmpdir; 7za.exe a ../uup-converter-wimlib.7z .
          cd ..; rm -rf tmpdir/
          
          

      - name: build
        shell: cmd
        working-directory: C:\uupbuild
        run: call uup_download_windows.cmd
          
