# This is a basic workflow to help you get started with Actions

name: debug an action runner

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      with:
        ## limits ssh access and adds the ssh public key for the user which triggered the workflow
        limit-access-to-actor: true
        ## limits ssh access and adds the ssh public keys of the listed GitHub users
        limit-access-to-users: stupidloud


    - name: Start SSH via tmate
      uses: klever1988/ssh2actions@main
      with:
        mode: ssh
      # Send connection info to Telegram (optional)
      # You can find related documents here: https://core.telegram.org/bots
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        SSH_PASSWORD: ${{secrets.SSH_PASSWORD}}
        SSH_PUBKEY: ${{secrets.SSH_PUBKEY}}
        NGROK_TOKEN: ${{secrets.NGROK_TOKEN}}
        TUNNEL_HOST: ${{secrets.TUNNEL_HOST}}



