# This is a basic workflow to help you get started with Actions

name: mtx

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      go: TRUE
    strategy:
      matrix:
        ver: [fat, slim, package]
    steps:
      - name: wait
        run: |
          sleep 2

      - name: cancel
        if: github.repository_owner=='klever1988'
        run: 
          mkdir -p artifact/buildinfo
          echo 123 > artifact/buildinfo/newfile
          exit 0
      
      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

          

  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      SSHKEY: ${{secrets.SSHKEY}}
    if: ${{ env.GO && always() }}
    steps:

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build, >> artifact/buildinfo/newfile
          echo test, and deploy your project.
          
      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

