# This is a basic workflow to help you get started with Actions

name: mtx

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      devices:
        description: 'build devices'
        default: '["x86", "r2s"]'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-matrix:
    name: Create Matrix
    runs-on: ubuntu-latest
    steps:
      - name: Set Matrix
        id: set-matrix
        env:
          MATRIX: ${{github.event.inputs.device}}
        run: |
          if [ $MATRIX=='' ]; then
            MATRIX='["x86","r2s"]'
          fi
          echo "::set-output name=matrix::$MATRIX"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }} 

  build:
    name: Test Workflow
    needs: create-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        device: ${{ fromJSON(needs.create-matrix.outputs.matrix) }}
    steps:
      - name: Matrix config
        env:
          MATRIX: ${{ toJSON(matrix) }}
        run: echo $MATRIX

