# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ver: [fat, slim, package]
    steps:
      - name: wait
        run: |
          sleep 60
      - name: cancelling
        if: ${{ github.repository_owner=='klever1988' && matrix.ver=="package" }}
        uses: andymckay/cancel-action@0.2

      - uses: actions/setup-node@v1
        with:
          ver: ${{ matrix.node }}
          

  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      SSHKEY: ${{secrets.SSHKEY}}
    if: github.repository_owner=='klever1988'
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
