# This is a basic workflow to help you get started with Actions

name: mtx

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-matrix:
    name: Create Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }} 
    steps:
      - name: Set Matrix
        id: set-matrix
        env:
          MATRIX_JSON: '
            { "include": [{
              "non-unique": true
            },{
              "non-unique": true
            }]}'
        run: echo "::set-output name=matrix::$MATRIX_JSON"

  build:
    name: Test Workflow
    needs: create-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJSON(needs.create-matrix.outputs.matrix) }}
    steps:
      - name: Matrix config
        env:
          MATRIX: ${{ toJSON(matrix) }}
        run: |
          echo "matrix = $MATRIX"

